import { chromium } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({headless:true, channel:process.env.BROWSER_CHANNEL || 'chrome'});
const context = await browser.newContext({acceptDownloads:true, viewport:{width:1365,height:1050}});
const page = await context.newPage();
const errors = [];
page.on('pageerror', e => errors.push(e.message));
page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
await mkdir('work/qa', {recursive:true});
await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5173/');
await page.waitForFunction(() => document.querySelector('#file-name').textContent === '虚构人物示例');
await page.screenshot({path:'work/qa/desktop.png',fullPage:true});
for (const [template,size,speed] of [['zoom','240','0.5'],['melt','320','1'],['rush','480','2']]) {
  await page.locator(`[data-template=${template}]`).click();
  await page.locator('#caption').fill(`测试-${template}`);
  await page.locator('#size').selectOption(size);
  await page.locator('#speed').fill(speed);
  const downloadP = page.waitForEvent('download');
  await page.locator('#export').click();
  const download = await downloadP;
  await download.saveAs(`work/qa/${template}.gif`);
  await page.waitForFunction(() => !document.querySelector('#export').disabled);
  assert.match(await page.locator('#status').textContent(), /已生成/);
}
// Upload a non-square real raster image through the input.
await page.locator('#file').setInputFiles('work/qa/desktop.png');
await page.waitForFunction(() => document.querySelector('#file-name').textContent === 'desktop.png');
await page.locator('summary').click();
await page.locator('#zoom').fill('1.5');
await page.locator('#x').fill('45');
await page.locator('#y').fill('-30');
await page.locator('[data-color="#f5dfe4"]').click();
await page.locator('#caption').fill('上传照片测试');
const uploadDownload = page.waitForEvent('download');
await page.locator('#export').click();
await (await uploadDownload).saveAs('work/qa/upload.gif');
await page.waitForFunction(() => !document.querySelector('#export').disabled);
await page.locator('#reset').click();
assert.equal(await page.locator('#zoom').inputValue(),'1');
await page.locator('#file').setInputFiles({name:'invalid.png',mimeType:'image/png',buffer:Buffer.from('not an image')});
await page.waitForFunction(() => document.querySelector('#status').textContent.includes('无法读取'));
await page.locator('#file').setInputFiles({name:'huge.jpg',mimeType:'image/jpeg',buffer:Buffer.alloc(10*1024*1024+1)});
await page.waitForFunction(() => document.querySelector('#status').textContent.includes('超过'));
await page.locator('#sample').click();
await page.waitForFunction(() => document.querySelector('#file-name').textContent === '虚构人物示例');
await page.getByRole('button',{name:'暂停预览',exact:true}).click();
assert.equal(await page.locator('#pause').getAttribute('aria-label'),'播放预览');
await page.getByRole('button',{name:'播放预览',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'work/qa/mobile.png',fullPage:true});
assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth),true);
await page.locator('#export').click();
await page.waitForFunction(() => !document.querySelector('#export').disabled);
assert.deepEqual(errors,[]);
await writeFile('work/qa/browser-result.json',JSON.stringify({templates:3,rasterUpload:true,errorRecovery:true,mobileWidth:390,consoleErrors:errors},null,2));
console.log('PASS: three downloads, raster upload, crop/settings, invalid and oversized input, reset, playback and mobile layout; no console errors');
await browser.close();
