import {chromium} from '@playwright/test';import {mkdir} from 'node:fs/promises';import assert from 'node:assert/strict';
const root=process.env.TEST_URL||'http://127.0.0.1:5173/',dir=process.env.QA_DIR||'work/caption';await mkdir(dir,{recursive:true});const b=await chromium.launch({headless:true,channel:'chrome'});
try{
 const p=await b.newPage({acceptDownloads:true}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(root);await p.waitForFunction(()=>document.querySelector('#face-status')?.textContent.includes('已定位'),null,{timeout:60000});
 await p.locator('.caption-controls .layer-fine summary').click();await p.locator('#pause').click();await p.locator('#caption').fill('文字测试');await p.locator('[data-caption-pos="8"]').click();await p.locator('#captionColor').fill('#ef4040');await p.locator('#captionSize').fill('42');assert.equal(await p.locator('#captionSize-value').innerText(),'42');await p.waitForTimeout(120);await p.locator('#preview').screenshot({path:`${dir}/top.png`});
 await p.locator('[data-caption-pos="96"]').click();await p.waitForTimeout(120);await p.locator('#preview').screenshot({path:`${dir}/bottom.png`});
 for(const style of ['meme','plain','band','shake']){await p.locator('#captionStyle').selectOption(style);const d=p.waitForEvent('download');await p.locator('#export').click();await(await d).saveAs(`${dir}/${style}.gif`);await p.waitForFunction(()=>!document.querySelector('#export').disabled);}
 await p.locator('#captionY').fill('8');await p.locator('#captionX').fill('0');await p.locator('#captionStyle').selectOption('band');
 await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:async text=>window.copied=text}}));await p.locator('#copy-recipe').click();const recipe=await p.evaluate(()=>window.copied);await p.goto('about:blank');await p.goto(recipe);await p.waitForFunction(()=>document.querySelector('#face-status')?.textContent.includes('已定位'),null,{timeout:60000});assert.equal(await p.locator('#captionX').inputValue(),'0');assert.equal(await p.locator('#captionY').inputValue(),'8');assert.equal(await p.locator('#captionStyle').inputValue(),'band');assert.equal(await p.locator('#captionColor').inputValue(),'#ef4040');
 await p.locator('#caption-reset').click();assert.equal(await p.locator('#captionColor').inputValue(),'#ffffff');assert.equal(await p.locator('#captionY').inputValue(),'96');
 for(const w of [390,320]){await p.setViewportSize({width:w,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}await p.locator('.caption-controls').scrollIntoViewIfNeeded();await p.screenshot({path:`${dir}/controls-mobile.png`});
 assert.equal(await p.locator('.product-footer a').count(),3);assert.equal(await p.locator('.product-footer a').first().getAttribute('href'),'https://github.com/swording-k/WechatMemeLab');assert.ok((await p.locator('.product-footer').innerText()).includes('联系作者'));
 await p.locator('.mode-nav a').nth(1).click();await p.waitForURL('**/video.html');assert.equal(await p.locator('.product-footer a').count(),3);assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
 console.log('PASS caption positions/colors/styles exports, sharing/reset, mobile, both product footers');
}finally{await b.close();}
