import '../style.css';import '../ui/mode-nav.css';import '../ui/product-footer.css';import './style.css';import {modeNav} from '../ui/mode-nav';import {productFooter} from '../ui/product-footer';import {storeVideo} from './handoff';
const plays=[
 {name:'我只是路过',symbol:'👀',caption:'我只是路过',prompt:'主体从画面左边小心探头偷看，与镜头对视后僵住半拍，然后迅速缩回画外。固定近景镜头，开头和结尾相似，动作清楚，有尴尬又嘴硬的反差。'},
 {name:'嘴硬到下一秒',symbol:'🥲',caption:'我没急',prompt:'主体故作镇定，努力忍住情绪，下一秒突然委屈大哭，最后快速擦掉眼泪强行恢复镇定。表情有连贯变化和短暂停顿，固定近景镜头，前后形成强烈反差。'},
 {name:'收到你消息的我',symbol:'🐶',caption:'你终于回我了',prompt:'主体起初无精打采，看到消息后瞬间兴奋，长出狗耳朵，像小狗一样向镜头扑过来，碰到画面后停顿，再退回初始位置。保持角色可识别，动作夸张可爱，固定近景镜头。'}
];
document.querySelector('#app')!.innerHTML=`<header class="site-header"><a class="brand" href="./"><img src="favicon.svg" alt=""><strong>怪相馆</strong></a><a href="./feedback.html">反馈 ↗</a></header><main>${modeNav('ai')}<div class="page-heading"><div><h1>把脑子里的怪相，<em>演出来。</em></h1><p>用一张照片，或从零创造角色。告诉它做什么，再把最有戏的几秒做成 GIF。</p></div></div><div class="ai-studio"><section class="ai-input"><h2>① 谁来演</h2><div class="ai-tabs"><button id="mode-photo" type="button" aria-pressed="true">用照片生成</button><button id="mode-text" type="button" aria-pressed="false">从文字生成</button></div><div id="photo-input"><label class="ai-upload">选自己的或朋友的照片<input id="photo" type="file" accept="image/png,image/jpeg,image/webp"><small>PNG / JPG / WebP · 最大 10 MB</small></label><img id="photo-preview" hidden alt="将提交给 MiniMax 的照片"><p id="photo-name">尚未选择照片</p><label class="ai-consent"><input id="consent" type="checkbox">生成时，这张照片和描述会发送给 MiniMax 处理。</label></div><h2>② 选个笑点，也能自由改</h2><div class="ai-plays">${plays.map((p,i)=>`<button type="button" data-play="${i}" aria-pressed="${i===0}"><span aria-hidden="true">${p.symbol}</span>${p.name}</button>`).join('')}</div><label for="prompt">角色和动作</label><textarea id="prompt" rows="5" maxlength="1600"></textarea><div class="ai-pair"><label>画风<select id="look"><option value="保持照片风格">保留原风格</option><option value="夸张的3D卡通">3D 卡通</option><option value="手绘漫画">手绘漫画</option></select></label><label>夸张程度<select id="energy"><option value="适度夸张，反应自然">自然一点</option><option value="夸张明显，有鲜明的喜剧停顿" selected>很有戏</option><option value="极度夸张的抽象喜剧动作">彻底放飞</option></select></label></div><label for="caption">回复文案（生成后再加到 GIF）</label><input id="caption" maxlength="60"><label id="access-label" hidden>内测口令<input id="access" type="password" autocomplete="off"></label><p id="price">正在连接生成服务…</p><button id="generate" class="ai-primary" type="button" disabled>生成动作视频</button></section><section class="ai-result"><h2>③ 看看这一秒有多怪</h2><div class="ai-output"><video id="video" controls playsinline muted loop hidden></video><div id="empty"><span aria-hidden="true">✦</span><p>生成的动作会出现在这里</p></div></div><p id="status" role="status" aria-live="polite">选一个玩法，改成你自己的笑点。</p><button id="resume" type="button" hidden>继续查询这次生成</button><button id="edit" class="ai-primary" type="button" hidden>加字、剪片段，做成 GIF →</button><a id="download" hidden download="怪相馆-AI动作视频.mp4">下载生成的视频</a><p class="ai-note">生成会消耗 AI 额度。加字、剪片段和本地转 GIF 不会再次调用 AI。离开页面不会自动取消 MiniMax 的生成任务。</p></section></div></main>${productFooter(true)}`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id)! as T,input=(id:string)=>$<HTMLInputElement>(id);
let mode:'photo'|'text'='photo',image='',active:string|undefined,videoBlob:Blob|undefined,url='',pollTimer:number|undefined,working=false,pending=false,configured=false,quota=false;
const base=(import.meta.env.VITE_AI_API_BASE||'/api/ai').replace(/\/$/,'');
const status=(text:string,error=false)=>{$('status').textContent=text;$('status').classList.toggle('error',error);};
async function request(path:string,body?:unknown){const response=await fetch(base+path,{method:body?'POST':'GET',headers:{...(body?{'Content-Type':'application/json'}:{}),...(input('access').value?{Authorization:'Bearer '+input('access').value}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:AbortSignal.timeout(60000)});const data=await response.json();if(!response.ok)throw Object.assign(new Error(data.error||'生成服务暂不可用'),{code:data.code});return data;}
function lock(value:boolean){working=value;for(const element of document.querySelectorAll<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement|HTMLButtonElement>('.ai-input input,.ai-input textarea,.ai-input select,.ai-input button'))element.disabled=value;$<HTMLButtonElement>('generate').disabled=value||pending||!configured||!quota;$('generate').textContent=value?'正在等待生成…':videoBlob?'再生成一条（消耗 AI 额度）':'生成动作视频';}
function price(){$('price').textContent=mode==='photo'?'MiniMax · 6 秒 / 768P · 参考费用 1.35 元／条':'MiniMax · 6 秒 / 768P · 参考费用 2 元／条';}
function choosePlay(index:number){const p=plays[index];$<HTMLTextAreaElement>('prompt').value=p.prompt;input('caption').value=p.caption;document.querySelectorAll<HTMLButtonElement>('[data-play]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.play)===index)));}
for(const button of document.querySelectorAll<HTMLButtonElement>('[data-play]'))button.onclick=()=>choosePlay(Number(button.dataset.play));choosePlay(0);
for(const next of ['photo','text'] as const)$('mode-'+next).onclick=()=>{mode=next;$('photo-input').hidden=next!=='photo';for(const key of ['photo','text'])$('mode-'+key).setAttribute('aria-pressed',String(key===next));price();};
input('photo').onchange=async()=>{const file=input('photo').files?.[0];if(!file)return;input('consent').checked=false;try{
 if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024)throw new Error('请选择 10 MB 内的 JPG、PNG 或 WebP 照片');
 const original=await createImageBitmap(file);try{if(original.width*original.height>40_000_000)throw new Error('照片像素过大，请缩小后上传');const c=document.createElement('canvas'),ratio=original.width/original.height,fit=ratio>=.4&&ratio<=2.5;let scale=1024/Math.max(original.width,original.height);if(fit&&Math.min(original.width,original.height)*scale<320)scale=320/Math.min(original.width,original.height);c.width=fit?Math.round(original.width*scale):1024;c.height=fit?Math.round(original.height*scale):1024;const ctx=c.getContext('2d')!;ctx.fillStyle='#ffffff';ctx.fillRect(0,0,c.width,c.height);const k=Math.min(c.width/original.width,c.height/original.height);ctx.drawImage(original,(c.width-original.width*k)/2,(c.height-original.height*k)/2,original.width*k,original.height*k);image=c.toDataURL('image/jpeg',.88);}finally{original.close();}
 $<HTMLImageElement>('photo-preview').src=image;$('photo-preview').hidden=false;$('photo-name').textContent=file.name;input('consent').checked=false;
 }catch(e){status(e instanceof Error?e.message:'照片读取失败',true);}finally{input('photo').value='';}};
async function completed(){const response=await fetch(`${base}/jobs/${active}/video`,{headers:input('access').value?{Authorization:'Bearer '+input('access').value}:{},signal:AbortSignal.timeout(120000)});if(!response.ok){const d=await response.json();throw new Error(d.error||'视频下载失败');}videoBlob=await response.blob();if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(videoBlob);const video=$<HTMLVideoElement>('video');video.src=url;video.hidden=false;$('empty').hidden=true;const a=$<HTMLAnchorElement>('download');a.href=url;a.hidden=false;$('edit').hidden=false;$('resume').hidden=true;pending=false;lock(false);status('动作已生成。挑最有戏的片段，加一句自己的话。');}
async function poll(){if(!active)return;clearTimeout(pollTimer);$('resume').hidden=true;try{const job=await request('/jobs/'+active);
 if(job.status==='success'){await completed();return;}if(['failed','unknown','submitting'].includes(job.status)){pending=job.status!=='failed';lock(false);status(job.error||'任务提交结果暂不确定，请保留记录，不要重复提交。',true);$('resume').hidden=false;return;}
 status({preparing:'正在准备生成…',queued:'MiniMax 正在排队…',processing:'动作正在生成，可能需要几分钟…'}[job.status as 'preparing'|'queued'|'processing']||'正在查询生成任务…');pollTimer=window.setTimeout(poll,10000);
 }catch(e){if((e as {code?:string}).code==='not_found'){pending=false;active=undefined;sessionStorage.removeItem('meme-ai-job');lock(false);status('这次生成没有成功提交，可以调整后重新生成。',true);return;}lock(false);status((e instanceof Error?e.message:'连接暂时中断')+'，可继续查询这次生成。',true);$('resume').hidden=false;}}
$('generate').onclick=async()=>{if(working||pending||!configured||!quota)return;const description=$<HTMLTextAreaElement>('prompt').value.trim();if(!description)return status('先描述角色要做什么',true);if(mode==='photo'&&(!image||!input('consent').checked))return status('请选择照片，并确认发送给 MiniMax 生成',true);
 if(url)URL.revokeObjectURL(url);url='';videoBlob=undefined;for(const id of ['video','edit','download'])$(id).hidden=true;$('empty').hidden=false;pending=true;active=crypto.randomUUID();sessionStorage.setItem('meme-ai-job',JSON.stringify({id:active,caption:input('caption').value}));lock(true);status('正在提交动作，请不要重复点击…');
 try{const prompt=`${mode==='text'?'创造一个清晰可辨的原创角色。':'保持照片中人物的身份和主要外观。'}${description}。${input('look').value}，${input('energy').value}。主体居中，大动作在小尺寸聊天里也能看懂。不要生成文字、字幕或标志。`;await request('/jobs',{id:active,mode,prompt,...(mode==='photo'?{image}:{})});await poll();}catch(e){lock(false);status((e instanceof Error?e.message:'提交未确认')+'。可查询本次任务，不要直接重复生成。',true);$('resume').hidden=false;}};
$('resume').onclick=()=>{lock(true);void poll();};$('edit').onclick=async()=>{if(!videoBlob)return;try{const id=await storeVideo(videoBlob,input('caption').value);location.href=`video.html?ai=${encodeURIComponent(id)}`;}catch(e){status(e instanceof Error?e.message:'无法导入视频',true);}};
$<HTMLVideoElement>('video').onerror=()=>status('浏览器无法预览这段视频，可下载后换浏览器打开。',true);
async function init(){
 try{
  const config=await request('/config');configured=Boolean(config.ready);quota=config.budget>config.spent;
  $('access-label').hidden=!config.needsAccess;
  if(!configured)throw new Error('AI 创作正在准备内测，生成服务尚未连接');
  price();lock(false);if(!quota)status('本轮生成额度暂未开放，已有视频仍可继续查询和编辑。');
  const saved=sessionStorage.getItem('meme-ai-job');
  if(saved){const job=JSON.parse(saved);pending=true;active=job.id;input('caption').value=job.caption||'';lock(false);$('resume').hidden=false;status('上次生成记录还在，点击继续查询，无需重新生成。');}
 }catch(e){status(e instanceof Error?e.message:'AI 创作暂不可用',true);$('price').textContent='生成服务暂不可用';}
}
void init();window.addEventListener('pagehide',()=>{clearTimeout(pollTimer);if(url)URL.revokeObjectURL(url);});
