import {modeNav} from '../ui/mode-nav';
export function mount(){document.querySelector('#app')!.innerHTML=`
<header><a href="${import.meta.env.BASE_URL}">← 照片整活</a><strong>怪相馆 <small>视频实验室</small></strong></header>
<main>${modeNav('video')}<h1>把这一秒，变成你的表情。</h1><p class="intro">视频在你的设备上处理。截一小段，加一句只有你们懂的话。</p>
<div class="studio"><section class="controls"><label class="upload">① 选一段视频<input id="file" type="file" accept="video/*"><small>最大 100 MB · 优先 MP4 · GIF 没有声音</small></label><p id="name">还没选视频</p>
<h2>② 选个起点</h2><div class="presets"><button data-mode="forward" aria-pressed="true">原片加字</button><button data-mode="bounce" aria-pressed="false">反复横跳</button><button data-mode="reverse" aria-pressed="false">倒带一下</button></div><p id="preset-note">保留原动作，配一句自己的话。</p>
<div class="pair"><label>开始（秒）<input id="start" type="number" min="0" step="0.1" value="0"></label><label>结束（秒）<input id="end" type="number" min="0.1" step="0.1" value="3"></label></div><small>每段最长 6 秒，来回预设会往返播放。</small>
<label>播放速度<select id="speed"><option value="0.5">0.5×</option><option value="1" selected>1×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></label>
<h2>③ 写点什么</h2><label for="text">文字（可拖动，最多三行）</label><textarea id="text" maxlength="60" rows="2" placeholder="比如：我真的没事">我真的没事</textarea>
<div class="pair"><label>字的颜色<input id="color" type="color" value="#ffffff"></label><label>字号<input id="font" type="range" min="0.06" max="0.2" step="0.01" value="0.12"></label></div>
<details><summary>文字位置和视频取景</summary><label>文字左右<input id="tx" type="range" min="0.05" max="0.95" step="0.01" value="0.5"></label><label>文字上下<input id="ty" type="range" min="0.05" max="0.95" step="0.01" value="0.85"></label><label>放大<input id="zoom" type="range" min="1" max="3" step="0.05" value="1"></label><label>取景左右<input id="cx" type="range" min="0" max="1" step="0.01" value="0.5"></label><label>取景上下<input id="cy" type="range" min="0" max="1" step="0.01" value="0.5"></label></details></section>
<section class="result"><div class="stage"><canvas id="preview" width="320" height="320" aria-label="视频表情预览，可拖动文字"></canvas><div id="empty">先选视频，看看哪一秒最有戏。</div></div><div class="pair"><button id="play" disabled>播放预览</button><span id="time">—</span></div>
<div class="pair"><label>画面比例<select id="ratio"><option value="original">保持原比例</option><option value="square">方形取景</option></select></label><label>导出长边<select id="size"><option value="240">240 px · 聊天推荐</option><option value="320">320 px · 更清晰</option></select></label></div>
<button id="export" class="primary" disabled>生成并下载 GIF →</button><button id="cancel" hidden>取消生成</button><progress id="progress" max="1" value="0" hidden></progress><p id="status" role="status" aria-live="polite">10 帧/秒 · 本地处理 · 无水印</p><img id="result" hidden alt="刚生成的 GIF，可长按查看保存选项"><a id="download" hidden download>再次下载 GIF</a><button id="share" hidden>打开分享菜单</button>
<p class="tip">手机：打开下载的 GIF → 分享 → 保存图像到相册 → 从社交平台的相册入口发送。动图播放以客户端实际支持为准。<a href="${import.meta.env.BASE_URL}#usage">查看截图教程</a></p></section></div></main>`;}
